name: Build and Release REAPER Plugin

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake -B build
      
    - name: Build
      run: cmake --build build
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: reaper-plugin-macos
        path: build/reaper_ReaperPluginExample.dylib

  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake -B build
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: reaper-plugin-windows
        path: build/Release/reaper_ReaperPluginExample.dll

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
    
    - name: Configure CMake
      run: cmake -B build
      
    - name: Build
      run: cmake --build build
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: reaper-plugin-linux
        path: build/reaper_ReaperPluginExample.so

  release:
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          reaper-plugin-macos/reaper_ReaperPluginExample.dylib
          reaper-plugin-windows/reaper_ReaperPluginExample.dll
          reaper-plugin-linux/reaper_ReaperPluginExample.so
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 