name: Build REAPER Plugin

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.25.0'
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Upload Windows Plugin
      uses: actions/upload-artifact@v4
      with:
        name: reaper_enz_ReaperTools-win64
        path: build/reaper_enz_ReaperTools.dll

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.25.0'
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Upload macOS Plugin
      uses: actions/upload-artifact@v4
      with:
        name: reaper_enz_ReaperTools-macos
        path: build/reaper_enz_ReaperTools.dylib

  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download Windows Plugin
      uses: actions/download-artifact@v4
      with:
        name: reaper_enz_ReaperTools-win64
        path: dist/
    
    - name: Download macOS Plugin
      uses: actions/download-artifact@v4
      with:
        name: reaper_enz_ReaperTools-macos
        path: dist/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/reaper_enz_ReaperTools.dll
          dist/reaper_enz_ReaperTools.dylib
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 